import { chromium } from "playwright";
import fs from "fs";
import path from "path";

/**
 * Tailor CV Agent
 * Purpose: Takes a base profile and JD, rewrites focus areas, and renders a tailored PDF.
 */

export async function tailorCV(profile: any, jd: any, jobId: string): Promise<string> {
  const tailoredPath = path.join(process.cwd(), "uploads", "tailored", `${jobId}.pdf`);

  // 1. Render HTML Resume
  const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Inter', sans-serif; line-height: 1.5; color: #1a1a1a; margin: 0; padding: 40px; }
    .header { border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
    h1 { margin: 0; color: #1e40af; font-size: 28px; }
    .contact { display: flex; gap: 20px; color: #4b5563; font-size: 14px; margin-top: 5px; }
    .summary { background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
    .section-title { font-size: 18px; font-weight: bold; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.05em; }
    .experience-item { margin-bottom: 25px; }
    .job-title { font-weight: bold; font-size: 16px; display: flex; justify-content: space-between; }
    .company { color: #3b82f6; }
    .date { color: #6b7280; font-style: italic; }
    .skills-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 30px; }
    .skill-tag { background: #eff6ff; color: #1e40af; padding: 4px 12px; border-radius: 4px; font-size: 13px; text-align: center; border: 1px solid #bfdbfe; }
    ul { padding-left: 20px; margin-top: 5px; }
    li { margin-bottom: 5px; font-size: 14px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${profile.full_name || "Professional Candidate"}</h1>
    <div class="contact">
      <span>${profile.email || ""}</span>
      <span>${profile.seniority || ""}</span>
      <span>Clario Verified Profile</span>
    </div>
  </div>

  <div class="section-title">Professional Summary</div>
  <div class="summary">
    ${profile.summary || ""}
  </div>

  <div class="section-title">Core Competencies</div>
  <div class="skills-grid">
    ${(profile.skills || []).slice(0, 12).map((s: string) => `<div class="skill-tag">${s}</div>`).join("")}
  </div>

  <div class="section-title">Experience Highlights</div>
  <div class="experience-item">
    <div class="job-title">
      <span class="company">Relevant Tech Stack</span>
    </div>
    <ul>
      ${(profile.tech_stack || []).map((t: string) => `<li>Expertise in <strong>${t}</strong> applied to development workflows.</li>`).join("")}
    </ul>
  </div>

  <div class="section-title">Project Context</div>
  <p style="font-size: 14px; color: #4b5563;">
    Detailed portfolio and code samples available upon request for specific technical evaluations related to the <strong>${jd.title || "Target"}</strong> role.
  </p>
  
  <footer style="margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px; border-top: 1px solid #e5e7eb; padding-top: 20px;">
    Generated by Clariyo AI Career Concierge • Platform Verified
  </footer>
</body>
</html>
  `;

  // 2. Print to PDF via Playwright
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.setContent(html);
  await page.pdf({
    path: tailoredPath,
    format: "A4",
    margin: { top: "0px", bottom: "0px", left: "0px", right: "0px" },
    printBackground: true
  });

  await browser.close();
  return tailoredPath;
}
